<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Aonik.Worker-36dc2491-8c26-4971-9b01-34cb50c12dab</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Aonik.Application.Tests" />
    <InternalsVisibleTo Include="Aonik.Api.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Quartz" Version="3.14.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.14.0" />
    <PackageReference Include="Quartz.Serialization.SystemTextJson" Version="3.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aonik.ServiceDefaults\Aonik.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Aonik.Application\Aonik.Application.csproj" />
    <ProjectReference Include="..\Aonik.Infrastructure\Aonik.Infrastructure.csproj" />
    <ProjectReference Include="..\Aonik.Platform\Aonik.Platform.csproj" />
    <ProjectReference Include="..\Aonik.Finance\Aonik.Finance.csproj" />
    <ProjectReference Include="..\Aonik.Ordering\Aonik.Ordering.csproj" />
    <ProjectReference Include="..\Aonik.Commerce\Aonik.Commerce.csproj" />
    <ProjectReference Include="..\Aonik.PersonalFinance\Aonik.PersonalFinance.csproj" />
    <ProjectReference Include="..\Aonik.Ai\Aonik.Ai.csproj" />
    <ProjectReference Include="..\Aonik.Agents\Aonik.Agents.csproj" />
  </ItemGroup>

</Project>
