module.exports = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'guides/getting-started',
        'deployment/local-development',
        'deployment/docker',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'Architecture',
        'architecture/overview',
        'architecture/clean-architecture',
        'architecture/data-flow',
        'architecture/module-organization',
        'architecture/technology-stack',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'Features',
      items: [{ type: 'autogenerated', dirName: 'features' }],
    },
    {
      type: 'category',
      label: 'Database',
      items: [{ type: 'autogenerated', dirName: 'database' }],
    },
    {
      type: 'category',
      label: 'Patterns & Decisions',
      items: [
        { type: 'autogenerated', dirName: 'patterns' },
        { type: 'autogenerated', dirName: 'decisions' },
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'Testing',
        'Troubleshooting',
        { type: 'autogenerated', dirName: 'deployment' },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    {
      type: 'category',
      label: 'Requirements',
      items: [{ type: 'autogenerated', dirName: 'requirements' }],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [{ type: 'autogenerated', dirName: 'contributing' }],
    },
  ],
};
