<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Aonik.Application\Aonik.Application.csproj" />
    <ProjectReference Include="..\Aonik.Platform\Aonik.Platform.csproj" />
    <ProjectReference Include="..\Aonik.Finance\Aonik.Finance.csproj" />
    <ProjectReference Include="..\Aonik.Ai\Aonik.Ai.csproj" />
    <ProjectReference Include="..\Aonik.Agents\Aonik.Agents.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Communication.Email" Version="1.0.0" />
    <PackageReference Include="Azure.Communication.Sms" Version="1.0.0" />
    <PackageReference Include="FluentStorage" Version="6.0.2" />
    <PackageReference Include="FluentStorage.Azure.Blobs" Version="6.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.1" />
    <PackageReference Include="Microsoft.FeatureManagement" Version="4.0.0" />
    <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="4.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.4" />
    <PackageReference Include="Quartz" Version="3.14.0" />
    <PackageReference Include="Scriban" Version="5.11.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
    <PackageReference Include="ZiggyCreatures.FusionCache" Version="2.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


</Project>
