import { useMemo, useState } from 'react';
import { Copy, Cog, Save, ShieldCheck, Webhook } from 'lucide-react';
import { toast } from 'sonner';

import { Badge } from '@/components/ui/badge';
import { Breadcrumb } from '@/components/ui/breadcrumb';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';

const webhookSettingsStorageKey = 'aonik:settings:webhooks';

const eventCatalog = [
  {
    key: 'order.status.changed',
    label: 'Order status changed',
    description: 'Order lifecycle transitions and resolution updates.',
  },
  {
    key: 'payment.intent.updated',
    label: 'Payment intent updated',
    description: 'Funding intent states and execution readiness.',
  },
  {
    key: 'ledger.entry.posted',
    label: 'Ledger entry posted',
    description: 'Double-entry postings generated by executed operations.',
  },
  {
    key: 'compliance.case.updated',
    label: 'Compliance case updated',
    description: 'Screening and review lifecycle events requiring action.',
  },
  {
    key: 'partner.transmission.failed',
    label: 'Partner transmission failed',
    description: 'Connector delivery failures and retry exhaustion.',
  },
];

interface WebhookSettingsState {
  endpointUrl: string;
  signingSecret: string;
  retryPolicy: '3' | '5' | '8';
  deadLetterEmail: string;
  enabledEvents: Record<string, boolean>;
}

function generateSigningSecret() {
  const bytes = new Uint8Array(18);
  if (typeof window !== 'undefined' && window.crypto?.getRandomValues) {
    window.crypto.getRandomValues(bytes);
  } else {
    for (let index = 0; index < bytes.length; index += 1) {
      bytes[index] = Math.floor(Math.random() * 256);
    }
  }

  const suffix = Array.from(bytes)
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');

  return `whsec_${suffix}`;
}

function getDefaultWebhookSettings(): WebhookSettingsState {
  return {
    endpointUrl: '',
    signingSecret: generateSigningSecret(),
    retryPolicy: '5',
    deadLetterEmail: 'alerts@aonik.ai',
    enabledEvents: {
      'order.status.changed': true,
      'payment.intent.updated': true,
      'ledger.entry.posted': true,
      'compliance.case.updated': false,
      'partner.transmission.failed': true,
    },
  };
}

function getInitialWebhookSettings(): WebhookSettingsState {
  const defaults = getDefaultWebhookSettings();
  try {
    const raw = localStorage.getItem(webhookSettingsStorageKey);
    if (!raw) return defaults;

    const parsed = JSON.parse(raw) as Partial<WebhookSettingsState>;
    return {
      ...defaults,
      ...parsed,
      enabledEvents: {
        ...defaults.enabledEvents,
        ...(parsed.enabledEvents ?? {}),
      },
    };
  } catch {
    return defaults;
  }
}

export function SettingsWebhooksPage() {
  const [settings, setSettings] = useState<WebhookSettingsState>(() => getInitialWebhookSettings());

  const enabledCount = useMemo(
    () => Object.values(settings.enabledEvents).filter(Boolean).length,
    [settings.enabledEvents]
  );

  const updateEvent = (eventKey: string, checked: boolean) => {
    setSettings((prev) => ({
      ...prev,
      enabledEvents: {
        ...prev.enabledEvents,
        [eventKey]: checked,
      },
    }));
  };

  const handleGenerateSecret = () => {
    setSettings((prev) => ({
      ...prev,
      signingSecret: generateSigningSecret(),
    }));
    toast.success('New signing secret generated. Save when ready.');
  };

  const handleCopySecret = async () => {
    try {
      await navigator.clipboard.writeText(settings.signingSecret);
      toast.success('Signing secret copied to clipboard.');
    } catch {
      toast.error('Clipboard copy failed.');
    }
  };

  const handleSave = () => {
    localStorage.setItem(webhookSettingsStorageKey, JSON.stringify(settings));
    toast.success('Webhook settings saved.');
  };

  return (
    <div className="h-full overflow-auto p-6">
      <Breadcrumb
        items={[
          { label: 'Settings', href: '/settings', icon: <Cog className="h-3.5 w-3.5" /> },
          { label: 'Webhooks', icon: <Webhook className="h-3.5 w-3.5" /> },
        ]}
        className="mb-4"
      />

      <div className="mb-6">
        <h1 className="text-2xl font-bold text-[var(--color-text-primary)]">Webhook Settings</h1>
        <p className="text-[var(--color-text-secondary)]">
          Configure reliable delivery for event notifications and secure webhook verification.
        </p>
      </div>

      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Endpoint Configuration</CardTitle>
            <CardDescription>Primary callback endpoint and signature controls.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="endpoint-url">Endpoint URL</Label>
              <Input
                id="endpoint-url"
                placeholder="https://api.partner.com/aonik/webhooks"
                value={settings.endpointUrl}
                onChange={(event) => setSettings((prev) => ({ ...prev, endpointUrl: event.target.value }))}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="dead-letter-email">Dead-letter alert email</Label>
              <Input
                id="dead-letter-email"
                type="email"
                value={settings.deadLetterEmail}
                onChange={(event) => setSettings((prev) => ({ ...prev, deadLetterEmail: event.target.value }))}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="signing-secret">Signing secret</Label>
              <div className="flex flex-col gap-2 sm:flex-row">
                <Input id="signing-secret" value={settings.signingSecret} readOnly className="font-mono text-xs" />
                <div className="flex gap-2">
                  <Button type="button" variant="outline" onClick={handleGenerateSecret}>
                    <ShieldCheck className="mr-2 h-4 w-4" />
                    Regenerate
                  </Button>
                  <Button type="button" variant="secondary" onClick={handleCopySecret}>
                    <Copy className="mr-2 h-4 w-4" />
                    Copy
                  </Button>
                </div>
              </div>
            </div>

            <div className="space-y-2">
              <Label>Retry policy</Label>
              <Select
                value={settings.retryPolicy}
                onValueChange={(value) => setSettings((prev) => ({ ...prev, retryPolicy: value as '3' | '5' | '8' }))}
              >
                <SelectTrigger className="w-full sm:w-64">
                  <SelectValue placeholder="Select retry policy" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="3">3 retries (fast)</SelectItem>
                  <SelectItem value="5">5 retries (balanced)</SelectItem>
                  <SelectItem value="8">8 retries (resilient)</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-start justify-between gap-4">
            <div>
              <CardTitle>Event Subscriptions</CardTitle>
              <CardDescription>Select which platform events are pushed to your endpoint.</CardDescription>
            </div>
            <Badge variant="secondary">{enabledCount} enabled</Badge>
          </CardHeader>
          <CardContent className="space-y-3">
            {eventCatalog.map((eventItem) => (
              <div
                key={eventItem.key}
                className="flex items-start justify-between gap-4 rounded-md border border-[var(--color-border-light)] px-4 py-3"
              >
                <div>
                  <p className="text-sm font-medium text-[var(--color-text-primary)]">{eventItem.label}</p>
                  <p className="text-xs text-[var(--color-text-tertiary)]">{eventItem.description}</p>
                  <p className="mt-1 font-mono text-[11px] text-[var(--color-text-tertiary)]">{eventItem.key}</p>
                </div>
                <Switch
                  checked={Boolean(settings.enabledEvents[eventItem.key])}
                  onCheckedChange={(checked) => updateEvent(eventItem.key, checked)}
                />
              </div>
            ))}
          </CardContent>
        </Card>

        <div className="flex justify-end">
          <Button onClick={handleSave}>
            <Save className="mr-2 h-4 w-4" />
            Save webhook settings
          </Button>
        </div>
      </div>
    </div>
  );
}
