FROM node:22-alpine AS build
WORKDIR /app

ARG VITE_AUTH_PROVIDER=azure-ad
ARG VITE_AZURE_AD_CLIENT_ID=
ARG VITE_AZURE_AD_TENANT_ID=
ARG VITE_AZURE_AD_REDIRECT_URI=
ARG VITE_AZURE_AD_API_SCOPE=
ARG VITE_AUTH0_DOMAIN=
ARG VITE_AUTH0_CLIENT_ID=
ARG VITE_AUTH0_REDIRECT_URI=
ARG VITE_AUTH0_AUDIENCE=
ARG VITE_API_BASE_URL=

ENV VITE_AUTH_PROVIDER=$VITE_AUTH_PROVIDER
ENV VITE_AZURE_AD_CLIENT_ID=$VITE_AZURE_AD_CLIENT_ID
ENV VITE_AZURE_AD_TENANT_ID=$VITE_AZURE_AD_TENANT_ID
ENV VITE_AZURE_AD_REDIRECT_URI=$VITE_AZURE_AD_REDIRECT_URI
ENV VITE_AZURE_AD_API_SCOPE=$VITE_AZURE_AD_API_SCOPE
ENV VITE_AUTH0_DOMAIN=$VITE_AUTH0_DOMAIN
ENV VITE_AUTH0_CLIENT_ID=$VITE_AUTH0_CLIENT_ID
ENV VITE_AUTH0_REDIRECT_URI=$VITE_AUTH0_REDIRECT_URI
ENV VITE_AUTH0_AUDIENCE=$VITE_AUTH0_AUDIENCE
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

COPY src/Aonik.AdminUi/package*.json ./
RUN npm ci

COPY src/Aonik.AdminUi/ ./
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
