<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <ItemGroup>
    <ProjectReference Include="..\Aonik.Api\Aonik.Api.csproj" />
    <ProjectReference Include="..\Aonik.Worker\Aonik.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>46012308-cf95-488f-a44a-580b75b6dbf9</UserSecretsId>
  </PropertyGroup>

</Project>
