name: payabo_mobile
description: Payabo Flutter mobile app
publish_to: none

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_analytics: ^12.0.4
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.4
  firebase_messaging: ^16.0.4
  go_router: 17.1.0
  flutter_riverpod: 3.3.1
  dio: ^5.7.0
  flutter_svg: ^2.0.10+1
  fl_chart: 1.1.1
  google_fonts: 8.0.2
  intl: 0.20.2
  flutter_secure_storage: 10.0.0
  shared_preferences: ^2.3.2
  pinput: 6.0.2
  file_picker: ^8.1.6
  image_picker: ^1.1.2
  local_auth: 3.0.1
  plaid_flutter: ^5.1.1
  youtube_player_iframe: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mba_logo.png
    - assets/images/slider-img-01.png
    - assets/images/slider-img-02.png
    - assets/images/slider-img-03.png
    - assets/images/slider-img-04.png
    - assets/images/slider-img-05.png
    - assets/images/slider-img-06.png
    - assets/images/setup-hero.png
    - assets/images/spending-empty-hero.png
    - assets/images/budget-hero.png
    - assets/images/illustrations/
    - assets/images/flags/
    - assets/images/demo_profile.jpg
    - assets/images/simi.png
