using Aonik.Infrastructure.Authentication.Configuration;
using FastEndpoints.Swagger;
using NSwag;
using NSwag.Generation.Processors.Security;
using Scalar.AspNetCore;

namespace Aonik.Api.Configuration;

public static class SwaggerConfiguration
{
    public static IServiceCollection AddAonikSwagger(
        this IServiceCollection services,
        IConfiguration configuration)
    {
        var authOptions = configuration.GetSection("Auth").Get<AuthOptions>()
            ?? throw new InvalidOperationException("Auth configuration is missing");

        var swaggerOptions = configuration.GetSection("Swagger").Get<SwaggerOptions>()
            ?? new SwaggerOptions();

        services.SwaggerDocument(options =>
        {
            options.DocumentSettings = settings =>
            {
                settings.Title = "AONIK API";
                settings.Version = "v1";
                settings.Description = "AONIK Financial Platform API with multi-tenant authentication";

                // Add JWT Bearer security definition
                settings.AddSecurity("Bearer", new OpenApiSecurityScheme
                {
                    Type = OpenApiSecuritySchemeType.OAuth2,
                    Description = "OAuth2 authentication with JWT Bearer tokens",
                    Flow = OpenApiOAuth2Flow.Implicit,
                    Flows = new OpenApiOAuthFlows
                    {
                        Implicit = CreateOAuth2Flow(authOptions, swaggerOptions)
                    }
                });

                // Apply security requirement globally
                settings.OperationProcessors.Add(new AspNetCoreOperationSecurityScopeProcessor("Bearer"));
            };
        });

        return services;
    }

    public static WebApplication UseAonikSwagger(
        this WebApplication app,
        IConfiguration configuration)
    {
        // Swagger is exposed strictly when IHostEnvironment.IsDevelopment() returns true.
        // The cloud "dev" slot is a deployment environment, not a development host —
        // its OpenAPI surface is intentionally NOT public.
        if (app.Environment.IsDevelopment())
        {
            var swaggerOptions = configuration.GetSection("Swagger").Get<SwaggerOptions>()
                ?? new SwaggerOptions();

            // Serve the OpenAPI JSON document generated by FastEndpoints/NSwag
            app.UseSwaggerGen(config =>
            {
                config.Path = "/swagger/{documentName}/swagger.json";
            });

            // Serve Scalar API Reference UI (replaces Swagger UI)
            app.MapScalarApiReference("/scalar", options =>
            {
                options.WithTitle("AONIK API")
                       .WithOpenApiRoutePattern("/swagger/{documentName}/swagger.json")
                       .WithDefaultHttpClient(ScalarTarget.CSharp, ScalarClient.HttpClient)
                       .ForceLightMode();

                // Configure OAuth2 if a client ID is set
                if (!string.IsNullOrEmpty(swaggerOptions.ClientId))
                {
                    options.AddPreferredSecuritySchemes("Bearer")
                           .AddImplicitFlow("Bearer", flow =>
                           {
                               flow.ClientId = swaggerOptions.ClientId;
                               flow.SelectedScopes = swaggerOptions.Scopes.ToArray();
                           });
                }
            }).AllowAnonymous();
        }

        return app;
    }

    private static OpenApiOAuthFlow CreateOAuth2Flow(AuthOptions authOptions, SwaggerOptions swaggerOptions)
    {
        string authorizationUrl;
        string tokenUrl;

        if (authOptions.Provider == "AzureAd")
        {
            // Azure AD OAuth2 endpoints
            var authority = authOptions.AzureAd.Authority;
            authorizationUrl = $"{authority}/authorize";
            tokenUrl = $"{authority}/token";
        }
        else if (authOptions.Provider == "Auth0")
        {
            // Auth0 OAuth2 endpoints
            var authority = authOptions.Auth0.Authority.TrimEnd('/');
            authorizationUrl = $"{authority}/authorize";
            tokenUrl = $"{authority}/oauth/token";
        }
        else if (authOptions.Provider == "Keycloak")
        {
            // Spec 029 added Keycloak as the third provider but never taught the
            // Swagger OAuth flow about it, so selecting it — the documented local
            // dev path — crashed the API at startup here rather than at a config
            // boundary. Keycloak's OIDC endpoints hang off the realm authority.
            var authority = authOptions.Keycloak.Authority.TrimEnd('/');
            authorizationUrl = $"{authority}/protocol/openid-connect/auth";
            tokenUrl = $"{authority}/protocol/openid-connect/token";
        }
        else
        {
            throw new InvalidOperationException($"Unsupported auth provider: {authOptions.Provider}");
        }

        var flow = new OpenApiOAuthFlow
        {
            AuthorizationUrl = authorizationUrl,
            TokenUrl = tokenUrl,
            Scopes = new Dictionary<string, string>()
        };

        // Add configured scopes
        foreach (var scope in swaggerOptions.Scopes)
        {
            flow.Scopes[scope] = $"Access to {scope}";
        }

        return flow;
    }
}

public class SwaggerOptions
{
    /// <summary>
    /// OAuth2 Client ID for API reference UI
    /// </summary>
    public string ClientId { get; set; } = string.Empty;

    /// <summary>
    /// OAuth2 scopes required for API access
    /// </summary>
    public List<string> Scopes { get; set; } = new();
}
