// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc0NKxNA4qnb_586iUmYwQZc1TN-s6tbs',
    appId: '1:946399382340:web:6b720e9cb364be5cff6511',
    messagingSenderId: '946399382340',
    projectId: 'payabo-b62c7',
    authDomain: 'payabo-b62c7.firebaseapp.com',
    storageBucket: 'payabo-b62c7.firebasestorage.app',
    measurementId: 'G-FN9R3SQ6JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlBEDQYRvHESxp-ML25KRBRT1JiFOxe9k',
    appId: '1:946399382340:android:bda0618167150316ff6511',
    messagingSenderId: '946399382340',
    projectId: 'payabo-b62c7',
    storageBucket: 'payabo-b62c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUOfyAruZu1s0RC2o_95AXMorAeaeVVLM',
    appId: '1:946399382340:ios:3ea46f5f1abc79c8ff6511',
    messagingSenderId: '946399382340',
    projectId: 'payabo-b62c7',
    storageBucket: 'payabo-b62c7.firebasestorage.app',
    iosBundleId: 'com.payabo.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUOfyAruZu1s0RC2o_95AXMorAeaeVVLM',
    appId: '1:946399382340:ios:c38d9807a30cd376ff6511',
    messagingSenderId: '946399382340',
    projectId: 'payabo-b62c7',
    storageBucket: 'payabo-b62c7.firebasestorage.app',
    iosBundleId: 'com.example.payaboMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc0NKxNA4qnb_586iUmYwQZc1TN-s6tbs',
    appId: '1:946399382340:web:faf1cb4c4aa8d6b1ff6511',
    messagingSenderId: '946399382340',
    projectId: 'payabo-b62c7',
    authDomain: 'payabo-b62c7.firebaseapp.com',
    storageBucket: 'payabo-b62c7.firebasestorage.app',
    measurementId: 'G-89DPLE0KF3',
  );
}
