import type { WorkspacePanelConfig } from './types';

export const workspacePanelRegistry: WorkspacePanelConfig[] = [
  {
    id: 'analytics',
    title: 'Analytics',
    description: 'Portfolio-level performance, trends, and AI insights.',
    type: 'internal',
    componentKey: 'analytics',
    route: '/analytics',
    defaultWidth: 720,
  },
  {
    id: 'search',
    title: 'Search',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/search',
  },
  {
    id: 'customers',
    title: 'Customers',
    type: 'internal',
    componentKey: 'customers-list',
    route: '/customers',
  },
  {
    id: 'billing',
    title: 'Billing',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/billing',
  },
  {
    id: 'billing-invoices',
    title: 'Invoices',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/billing/invoices',
  },
  {
    id: 'billing-invoices-new',
    title: 'Create Invoice',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/billing/invoices/new',
  },
  {
    id: 'billing-dunning',
    title: 'Dunning Plans',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/billing/dunning',
  },
  {
    id: 'payments',
    title: 'Payments',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/payments',
  },
  {
    id: 'payments-transactions',
    title: 'Transactions',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/payments/transactions',
  },
  {
    id: 'payments-payouts',
    title: 'Payouts',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/payments/payouts',
  },
  {
    id: 'payments-refunds',
    title: 'Refunds',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/payments/refunds',
  },
  {
    id: 'payments-chargebacks',
    title: 'Chargebacks',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/payments/chargebacks',
  },
  {
    id: 'orders',
    title: 'Orders',
    type: 'internal',
    componentKey: 'orders-landing',
    route: '/orders',
  },
  {
    id: 'orders-bill-payments-new',
    title: 'Create Bill Payment',
    type: 'internal',
    componentKey: 'bill-payment-form',
    route: '/orders/bill-payments/new',
  },
  {
    id: 'orders-activity',
    title: 'Order Activity',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/orders/activity',
  },
  {
    id: 'ledger',
    title: 'Ledger',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/ledger',
  },
  {
    id: 'ledger-accounts',
    title: 'Accounts',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/ledger/accounts',
  },
  {
    id: 'ledger-journal-entries',
    title: 'Journal Entries',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/ledger/journal-entries',
  },
  {
    id: 'ledger-reconciliation',
    title: 'Reconciliation',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/ledger/reconciliation',
  },
  {
    id: 'ai',
    title: 'AI & Agents',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/ai',
  },
  {
    id: 'ai-agents',
    title: 'Agents',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/ai/agents',
  },
  {
    id: 'ai-models',
    title: 'AI Models',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/ai/models',
  },
  {
    id: 'ai-orchestrator',
    title: 'Orchestrator',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/ai/orchestrator',
  },
  {
    id: 'access-users',
    title: 'Users',
    type: 'internal',
    componentKey: 'access-users',
    route: '/access/users',
  },
  {
    id: 'access-roles',
    title: 'Roles',
    type: 'internal',
    componentKey: 'access-roles',
    route: '/access/roles',
  },
  {
    id: 'access-permissions',
    title: 'Permissions',
    type: 'internal',
    componentKey: 'access-permissions',
    route: '/access/permissions',
  },
  {
    id: 'catalog',
    title: 'Catalog',
    type: 'internal',
    componentKey: 'catalog-landing',
    route: '/catalog',
  },
  {
    id: 'catalog-countries',
    title: 'Countries',
    type: 'internal',
    componentKey: 'catalog-countries',
    route: '/catalog/countries',
  },
  {
    id: 'catalog-categories',
    title: 'Categories',
    type: 'internal',
    componentKey: 'catalog-categories',
    route: '/catalog/categories',
  },
  {
    id: 'catalog-billers',
    title: 'Billers',
    type: 'internal',
    componentKey: 'catalog-billers',
    route: '/catalog/billers',
  },
  {
    id: 'tenants',
    title: 'Tenants',
    type: 'internal',
    componentKey: 'tenants',
    route: '/tenants',
  },
  {
    id: 'settings',
    title: 'Settings',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/settings',
  },
  {
    id: 'settings-general',
    title: 'General',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/settings/general',
  },
  {
    id: 'settings-autonumbering',
    title: 'Autonumbering',
    type: 'internal',
    componentKey: 'autonumbering',
    route: '/settings/autonumbering',
  },
  {
    id: 'settings-fx-rates',
    title: 'FX Rates',
    type: 'internal',
    componentKey: 'fx-rates',
    route: '/settings/fx-rates',
  },
  {
    id: 'settings-webhooks',
    title: 'Webhooks',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/settings/webhooks',
  },
  {
    id: 'settings-api-keys',
    title: 'API Keys',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/settings/api-keys',
  },
  {
    id: 'settings-audit-logs',
    title: 'Audit Logs',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/settings/audit-logs',
  },
  {
    id: 'cms',
    title: 'Content',
    type: 'internal',
    componentKey: 'placeholder',
    route: '/cms',
  },
  {
    id: 'cms-content-blocks',
    title: 'Content Blocks',
    type: 'internal',
    componentKey: 'content-blocks',
    route: '/cms/content-blocks',
  },
  {
    id: 'cms-media',
    title: 'Media Library',
    type: 'internal',
    componentKey: 'media-library',
    route: '/cms/media',
  },
  {
    id: 'invoice-manager',
    title: 'Invoice Manager',
    description: 'Create, manage, and track invoices with AI-assisted insights.',
    type: 'internal',
    componentKey: 'invoice-manager',
    appCardId: '1',
    defaultWidth: 520,
  },
  {
    id: 'reconciliation-hub',
    title: 'Reconciliation Hub',
    description: 'AI-powered matching and discrepancy detection.',
    type: 'internal',
    componentKey: 'reconciliation-hub',
    appCardId: '2',
    defaultWidth: 520,
  },
  {
    id: 'cash-flow-forecaster',
    title: 'Cash Flow Forecaster',
    description: 'Predict cash positions and run scenario planning.',
    type: 'internal',
    componentKey: 'cash-flow-forecaster',
    appCardId: '3',
    defaultWidth: 520,
  },
  {
    id: 'fraud-detection',
    title: 'Fraud Detection',
    description: 'Real-time anomaly detection and explainable alerts.',
    type: 'internal',
    componentKey: 'fraud-detection',
    appCardId: '4',
    defaultWidth: 520,
  },
];

export const defaultWorkspaceLayoutPanels = ['invoice-manager', 'reconciliation-hub'];

export function getWorkspacePanelConfig(panelId: string) {
  return workspacePanelRegistry.find((panel) => panel.id === panelId);
}

export function getWorkspacePanelForApp(appCardId: string) {
  return workspacePanelRegistry.find((panel) => panel.appCardId === appCardId);
}

export function getWorkspacePanelForRoute(route?: string) {
  if (!route) return undefined;
  return workspacePanelRegistry.find((panel) => panel.route === route);
}
