<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="7.1.1" />
    <PackageReference Include="FastEndpoints.Swagger" Version="7.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aonik.Application\Aonik.Application.csproj" />
    <ProjectReference Include="..\Aonik.Infrastructure\Aonik.Infrastructure.csproj" />
    <ProjectReference Include="..\Aonik.ServiceDefaults\Aonik.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
